HashSet<Integer> o = new HashSet<>();
        o.add(0);
        o.add(2);
        o.add(6);
        o.add(3);
        o.add(6);
        o.add(2);
        o.add(5);
        o.add(7);
        o.add(9);
        System.out.println(o);